security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SONATA_ADMIN: ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SONATA_ADMIN

    firewalls:
        admin:
            pattern:   ^/admin
            http_basic:
                realm: "RSHQ Admin"
            logout:
                path: sonata_user_admin_security_logout
                target: sonata_admin_redirect
            anonymous: true

        main:
            pattern:   ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path: fos_user_security_logout
                target: home_redirect
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_SONATA_ADMIN }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

    acl:
        connection: default

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_SUPER_ADMIN' }
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512
