services:
    shrq_symposium_registration:
        class: SHRQ\SymposiumBundle\Form\RegistrationFormType
        tags:
            -  { name: form.type }
        arguments: [%fos_user.model.user.class%]
    shrq_symposium_profile:
        class: SHRQ\SymposiumBundle\Form\ProfileFormType
        tags:
            -  { name: form.type }
        arguments: [%fos_user.model.user.class%]